#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: _MNL-CMN | install | Check for presence of group '{{ manila_group }}'
  command: "grep -q {{ manila_group }} /etc/group"
  ignore_errors: True
  register: manila_group_chk_result

- name: _MNL-CMN | install | Add group '{{ manila_group }}'
  group: name={{ manila_group }}
  when: manila_group_chk_result|failed

- name: _MNL-CMN | install | Check '{{ manila_home_dir }}' dir exists
  stat:
    path={{ manila_home_dir }}
  register: manila_home_dir_result

- name: _MNL-CMN | install | Fail when '{{ manila_home_dir }}' does not exist
  fail:
    msg: "{{ manila_home_dir }} does not exist"
  when: not manila_home_dir_result.stat.exists or not manila_home_dir_result.stat.isdir

- name: _MNL-CMN | install | Check for presence of user '{{ manila_user }}'
  command: "id {{ manila_user }}"
  ignore_errors: True
  register: manila_user_chk_result

- name: _MNL-CMN | install | Add user '{{ manila_user }}'
  user:
    name: "{{ manila_user }}"
    group: "{{ manila_group }}"
    createhome: no
    home: "{{ manila_home_dir }}"
    shell: /sbin/nologin
  when: manila_user_chk_result|failed
