#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: MNL-SHR | configure  | Copy manila client env file
  template:
    src: "{{ item }}"
    dest: "{{ ardanauser_home }}"
    owner: "{{ ardanauser }}"
    group: "{{ ardanauser }}"
    mode: "0600"
  with_items:
    - manila.osrc

- name: MNL-SHR | configure | Create manila audit directory structure if necessary
  file:
    path: "{{ manila_audit_log_base_location }}/manila"
    state: directory
    owner: "{{ manila_user }}"
    group: "{{ manila_group }}"
    mode: 0755
  become: yes
  when: manila_api_audit_enable | bool

- name: MNL-SHR | configure | Create/Modify manila audit log files
  file:
    path: "{{ manila_audit_log_base_location }}/manila/{{ item }}"
    state: touch
    owner: "{{ manila_user }}"
    group: adm
    mode: 0640
  become: yes
  with_items:
    - manila-audit.log
  when: manila_api_audit_enable | bool
