#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: MNL-API | keystone_get_conf | Get a domain scoped token
  keystone_v3:
    endpoint: "{{ manila_keystone.admin_url }}"
    login_username: "{{ manila_keystone.admin_user }}"
    login_password: "{{ manila_keystone.admin_password }}"
    login_user_domain_name: "{{ manila_keystone.default_domain_name }}"
    login_domain_name: "{{ manila_keystone.default_domain_name }}"
    action: "token_get"
  run_once: true
  register: manila_domain_scoped_token_result

- name: MNL-API | keystone_get_conf | Find manila internal project id
  keystone_v3:
    action: "find_project"
    login_token: "{{ manila_domain_scoped_token_result.result }}"
    endpoint: "{{ manila_keystone.admin_url }}"
    project_domain_name: "Default"
    project_name: "{{ manilainternal_project_name }}"
  run_once: true
  register: manilainternal_find_project_result

- name: MNL-API | keystone_get_conf | Set manila internal project id fact
  set_fact:
    manilainternal_project_id: >-
      {{ manilainternal_find_project_result.result.id }}
  run_once: true

- name: MNL-API | keystone_get_conf | Find manila internal user id
  keystone_v3:
    action: "find_user"
    login_token: "{{ manila_domain_scoped_token_result.result }}"
    endpoint: "{{ manila_keystone.admin_url }}"
    user_domain_name: "Default"
    user_name: "{{ manilainternal_user }}"
  run_once: true
  register: manilainternal_find_user_result

- name: MNL-API | keystone_get_conf | Set manila internal user id fact
  set_fact:
    manilainternal_user_id: >-
      {{ manilainternal_find_user_result.result.id }}
  run_once: true

- name: MNL-API | keystone_get_conf | Display manila internal project id and user id
  debug:
    msg: >
      Manila Internal Project id is {{ manilainternal_project_id }}
      and User id is {{ manilainternal_user_id }}
  run_once: true
